INSERT INTO PUBLIC.USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('n1', 'l1', 'e1', '2023-05-01');
INSERT INTO PUBLIC.USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('n2', 'l2', 'e2', '2023-05-01');
INSERT INTO PUBLIC.USERS (NAME, LOGIN, EMAIL, BIRTHDAY)
VALUES ('n3', 'l3', 'e3', '2023-05-01');

INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION)
VALUES ('f1', 'd1', '2023-05-01', 100);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION)
VALUES ('f2', 'd2', '2023-05-07', 100);
INSERT INTO PUBLIC.FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION)
VALUES ('f3', 'd2', '2022-05-01', 100);

INSERT INTO PUBLIC.GENRE (TITLE)
VALUES ('COMEDY');
INSERT INTO PUBLIC.GENRE (TITLE)
VALUES ('ACTION');
INSERT INTO PUBLIC.GENRE (TITLE)
VALUES ('THRILLER');

INSERT INTO PUBLIC.RATING (TITLE)
VALUES ('PG');
INSERT INTO PUBLIC.RATING (TITLE)
VALUES ('PG_13');
INSERT INTO PUBLIC.RATING (TITLE)
VALUES ('R');

INSERT INTO PUBLIC.FRIEND_STATUS (STATUS_TITLE)
VALUES ('UNCONFIRMED');
INSERT INTO PUBLIC.FRIEND_STATUS (STATUS_TITLE)
VALUES ('CONFIRMED');
INSERT INTO PUBLIC.FRIEND_STATUS (STATUS_TITLE)
VALUES ('UNKNOWN');

INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID)
VALUES (1, 1);
INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID)
VALUES (2, 2);
INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID)
VALUES (3, 3);
INSERT INTO PUBLIC.FILM_GENRE (FILM_ID, GENRE_ID)
VALUES (1, 2);

INSERT INTO PUBLIC.FILM_LIKES (FILM_ID, USER_ID)
VALUES (1, 1);
INSERT INTO PUBLIC.FILM_LIKES (FILM_ID, USER_ID)
VALUES (1, 2);
INSERT INTO PUBLIC.FILM_LIKES (FILM_ID, USER_ID)
VALUES (2, 2);
INSERT INTO PUBLIC.FILM_LIKES (FILM_ID, USER_ID)
VALUES (3, 3);

INSERT INTO PUBLIC.FILM_RATING (FILM_ID, RATING_ID)
VALUES (1, 1);
INSERT INTO PUBLIC.FILM_RATING (FILM_ID, RATING_ID)
VALUES (2, 2);
INSERT INTO PUBLIC.FILM_RATING (FILM_ID, RATING_ID)
VALUES (3, 3);

INSERT INTO PUBLIC.USER_FRIENDS (USER_ID, FRIEND_ID, STATUS_ID)
VALUES (1, 2, DEFAULT);
INSERT INTO PUBLIC.USER_FRIENDS (USER_ID, FRIEND_ID, STATUS_ID)
VALUES (2, 3, 2);
INSERT INTO PUBLIC.USER_FRIENDS (USER_ID, FRIEND_ID, STATUS_ID)
VALUES (3, 1, 3);


